[package]
name = "a-star-prototype"
version = "0.1.0"
authors = ["franciscoaguirre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
bevy_mod_picking = "0.3.1"
